### ISSUE TITLE
pydap.responses.netcdf will not work for certain >2GB files

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pydap.responses.netcdf#2]
This needs to be confirmed, but I was documenting the specifics of the NetCDF file that is returned by the data portal and it appears that under no circumstances will the handler create a 64-bit offset file (i.e. one that can handle files of size > 4GB). If if this the case, it should be easy to fix by adding a version=2 parameter to the call to netcdf_file() (pydap.responses.netcdf.**init**.py:18). But someone needs to go through this and make sure that it works.

**Comment by basilveerman** [comment]
Investigated requests with different data sources, variables, domain, time range, and final file size. Results are mixed.

Vic Data
------------

Request | Dump | View
------------|---------|---------
[Full File](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc)| no errors | `ncview: posixio.c:431: px_get: Assertion 'offset >= 0' failed. Aborted (core dumped)`
[bf](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?bf) | no errors | no errors
[R](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?R) | no errors | no errors
[aet](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?aet) | no errors | no errors
[swe](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?swe) | `ncdump: v1hpg.c:1156: NC_computeshapes: Assertion 'ncp->begin_rec > 0' failed.` | `ncview: v1hpg.c:1156: NC_computeshapes: Assertion 'ncp->begin_rec > 0' failed.`
[sm](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?sm) | `ncdump: v1hpg.c:1156: NC_computeshapes: Assertion 'ncp->begin_rec > 0' failed.` | `ncview: v1hpg.c:1156: NC_computeshapes: Assertion 'ncp->begin_rec > 0' failed.`
[swe w/params](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?swe[0:54786][0:162][0:214]&) | `ncdump: v1hpg.c:1156: NC_computeshapes: Assertion 'ncp->begin_rec > 0' failed.` | `ncview: v1hpg.c:1156: NC_computeshapes: Assertion 'ncp->begin_rec > 0' failed.`
[Limit time](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?swe[0:60][0:162][0:214]&) | no errors | no errors
[Limit domain](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?swe[0:54786][75:78][100:103]&) | no errors | no errors
[4,626,217,380 bytes swe req](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?swe[0:33000][0:162][0:214]&) | no errors | no errors
[4,205,665,380 bytes swe req](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?swe[0:30000][0:162][0:214]&) | `ncdump: v1hpg.c:1156: NC_computeshapes: Assertion 'ncp->begin_rec > 0' failed.` | `ncview: v1hpg.c:1156: NC_computeshapes: Assertion 'ncp->begin_rec > 0' failed.`
[5,607,505,380 bytes swe req](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?swe[0:40000][0:162][0:214]&) | no errors | no errors
[7,009,345,380 bytes swe req](http://tools.pacificclimate.org/dataportal/hydro_model_out/data/5var_day_CGCM3_A2_run1_19500101-20991231.nc.nc?swe[0:50000][0:162][0:214]&) | `ncdump: v1hpg.c:1156: NC_computeshapes: Assertion 'ncp->begin_rec > 0' failed.` | `ncview: v1hpg.c:1156: NC_computeshapes: Assertion 'ncp->begin_rec > 0' failed.`


BCSD Data
------------
Request | Dump | View
------------|---------|---------
[1.2GB req](http://tools.pacificclimate.org/dataportal/downscaled_gcms/data/pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc.nc?tasmax[0:55152][82:149][170:247]&) | no errors | no errors
[6.7GB req](http://tools.pacificclimate.org/dataportal/downscaled_gcms/data/pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc.nc?tasmax[0:55152][85:223][139:356]&) | no errors | no errors

**Comment by jameshiebert** [comment]
Looking at this issue further today, and I'm pretty sure that it should be a one-line patch to support 4+ GB files. [Here](https://github.com/pacificclimate/pydap.responses.netcdf/blob/master/src/pydap/responses/netcdf/__init__.py#L21), we can simply replace:

```
self.nc = netcdf_file(None)
```

with:

```
self.nc = netcdf_file(None, version=2)
```

Needs to be tested.

**Comment by jameshiebert** [comment]
@corviday Tracked down the limiting factor here from [the Unidata docs](https://www.unidata.ucar.edu/software/netcdf/netcdf/NetCDF-Classic-Format-Limitations.html):

> If you don't use the unlimited dimension, only one variable can exceed 2 GiB in size, but it can be as large as the underlying file system permits. It must be the last variable in the dataset, and the offset to the beginning of this variable must be less than about 2 GiB.

So at this point, many of our larger BCCAQv2 requests will be affected by this.

Fix in progress.

**Comment by corviday** [comment]
I have made the one-line replacement and tested it by downloading a few files above and below the 2GB limit from each portal. Everything seems to work correctly. The files have magic header byte '\002' as expected, and they are all viewable by ncview, including BCCAQv2 files with size >2GB and the "main" variable not in the last position.

**Comment by jameshiebert** [comment]
Hooray! Should we add to this patch code that ensures the main variable is not in the last position? Order them by size, maybe?

**Comment by corviday** [comment]
I think so? The tools I'm testing with don't seem to actually require that, but the netCDF [64-bit offset standard does](https://www.unidata.ucar.edu/software/netcdf/netcdf/NetCDF-64-bit-Offset-Format-Limitations.html#NetCDF-64-bit-Offset-Format-Limitations):

> No fixed-size variable can require more than 2^32 - 4 bytes (i.e. 4GiB - 4 bytes, or 4,294,967,292 bytes) of storage for its data, unless it is the last fixed-size variable and there are no record variables. When there are no record variables, the last fixed-size variable can be any size supported by the file system, e.g. terabytes. 

So there may well be other tools that do require this.
