### ISSUE TITLE
Responder may hang when serving files without any record variables

### ISSUE THREAD

**Issue by corviday** [pacificclimate/pydap.responses.netcdf#4]
[record_generator](https://github.com/pacificclimate/pydap.responses.netcdf/blob/90134a01f5980ecbfb85096734db05fc00765da6/src/pydap/responses/netcdf/__init__.py#L126), which iterates over a files record variables, may not exit the `while True:` loop if the netCDF file has _no_ record variables. This results in the process just hanging.

However, this error does not occur with _all_ data requests made against files without record variables, which is puzzling.

**Comment by jameshiebert** [comment]
`while True:` :man_facepalming: Why on earth did I ever think that was a good idea...
