### ISSUE TITLE
Response length differs from calculated content-length header

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pydap.responses.netcdf#6]
It is turning up that many of the BCCAQv2 datasets return data that has a different content-length than what the response says it should have. However, the NetCDF library happily opens up the responses without error. It's possible that it's creating a well-formed file, but with some offset mistake somewhere (most of the error files are off by 2-6 bytes) that makes the data == garbage anywhere after the offest problem.

This needs to be investigated. Suspect code could be in the [`pupynere-pdp` repository](https://github.com/pacificclimate/pupynere-pdp) or here. Review the [NetCDF3 spec](https://www.unidata.ucar.edu/software/netcdf/netcdf/File-Format-Specification.html) for any possible missed offsets.

**Comment by jameshiebert** [comment]
I think that I have a leading hypothesis for this. Reading part of [the NetCDF spec](https://www.unidata.ucar.edu/software/netcdf/netcdf/File-Format-Specification.html):

```
     values  := [bytes] | [chars] | [shorts] | [ints] | [floats] | [doubles]
     string  := nelems  [chars]
     bytes   := [BYTE ...]  padding
     chars   := [CHAR ...]  padding
     shorts  := [SHORT ...]  padding
     ints    := [INT ...]
     floats  := [FLOAT ...]
     doubles := [DOUBLE ...]
     padding := <0, 1, 2, or 3 bytes to next 4-byte boundary>
                               // In header, padding is with 0 bytes.  In
                               // data, padding is with variable's fill-value.
```

So variables get padded out to the 4-byte boundary. One difference that we have overlooked between the BCCAQ and BCCAQv2 data is that the BCCAQ data were all stored as 4-byte float values, while the BCCAQv2 data are all [packed](http://james.hiebert.name/blog/work/2015/04/18/NetCDF-Scale-Factors.html) into 2-byte char types.

This means that for certain requests, e.g. requests with odd-length arrays, the variable length will not fall on the 2-byte boundary and will require packing. Indeed all of the requests that were failing for you were `t=2-8` (length 7) with 1 x and 1 y. While your requests that were `t=2-7` (length 6, even) would pass. The first request in our test suite that fails is `t=2-1000` (length 999) with 1 x and 1 y.

So, it *seems* to make sense. I haven't confirmed that this is definitely the case, but it's a good working hypothesis.

There appear to be [a couple](https://github.com/pacificclimate/pupynere-pdp/blob/master/pupynere.py#L512) [places](https://github.com/pacificclimate/pupynere-pdp/blob/master/pupynere.py#L520) where [`pupynere-pdp`](https://github.com/pacificclimate/pupynere-pdp/) adds padding to the size calculations, so it's likely that the content-length is correct, while this package's generator functions do not add the padding where required.

**Comment by corviday** [comment]
That seems like a very plausible hypothesis.

**Comment by jameshiebert** [comment]
Viable patch in progress... looking good, but I'll hold out for the full test run.

**Comment by jameshiebert** [comment]
Having some trouble w/ the intersection of data sets with record variables and data sets with packed data; please stand by...
